### ISSUE TITLE
Can't find the skeleton.

### ISSUE THREAD

**Issue by Durlabh-Ashok** [tranduyhung/grav-theme-x-corporation#1]
Hello Can you upload the full skeleton here including the pages.
I meant this one (http://www.peaceofmindwebsite.com/skeletons/x-corporation/)
Thanks

**Comment by tranduyhung** [comment]
You can download it here: https://github.com/tranduyhung/grav-skeleton-x-corporation/releases

**Comment by Durlabh-Ashok** [comment]
Thank You :) :+1:
