### ISSUE TITLE
Favicon Doesn't work

### ISSUE THREAD

**Issue by jared461** [tranduyhung/grav-theme-x-corporation#13]
The Favicon doesn't work and comes blank. Only shows on admin module and the home page. All other pages using the skeleton don't work (i.e. About, Contact etc.).

**Comment by pbt39ppc** [comment]
cannot confirm that.
dont remember how, but i have favicon working.
maybe thats because i have put it in all available locations (site root, antimatter, x-corp)
cant remember now, but plannet to figure it out on next week...
