### ISSUE TITLE
If i don't want show tag H1?

### ISSUE THREAD

**Issue by lukevhf** [tranduyhung/grav-theme-x-corporation#15]
hi, if i don't want show tag h1 in all pages of carousel and i don't write nothing why appear tag h1 empty in all slide...
Is possible to eliminate this like if i don't write nothing in admin for 2/3 slides i don't want appear when i read html code...
thank and sorry for my italian english

**Comment by tranduyhung** [comment]
Do you mean h2 element? I don't see any h1 elements in this template. h2 element is used to show page's title which is almost used in all pages and there is no options to turn it off. If you want to can change the line

````
 <h2>{{ page.title }}</h2>
````

in the files in user/themes/x-corporation/templates/modular/ to

````
{% if page.title %}<h2>{{ page.title }}</h2>{% endif %}
````

**Comment by lukevhf** [comment]
Sorry, my english is very bad..
I want know if in carousel page is possible, if i don't write nothing in header in 2 or 3 slide, don't show in html tag h1 like this
<h1></<h1>
thanks

**Comment by tranduyhung** [comment]
I see. In user/themes/x-corporation/templates/modular/carousel.html.twig you change the line

````
<h1>{{ slide.heading }}</h1>

to

````
{% if slide.heading %}<h1>{{ slide.heading }}</h1>{% endif %}

**Comment by lukevhf** [comment]
thanks
