### ISSUE TITLE
menu issue

### ISSUE THREAD

**Issue by diomed** [tranduyhung/grav-theme-x-corporation#2]
hello!

This is very nice theme, however I'm having some problems with menu.
On demo, when I click Features, nice drop down menu appears with all
those links that are probably subpages of the main page.

However, when I hover over my main page with subpages,
it displays no text only one blank row.

**Comment by tranduyhung** [comment]
It is difficult to say if I don't see your page structure. You can check [the skeleton](https://github.com/tranduyhung/grav-skeleton-x-corporation) to get some ideas of how the submenu works.

**Comment by diomed** [comment]
can't you somehow recode it, so it could pick up dropdown automatically, like it does in antimatter?
because there I see dropdown menu for articles , and here not.

**Comment by tranduyhung** [comment]
Dropdown is built automatically, as  you can see in the skeleton (http://peaceofmindwebsite.com/skeletons/x-corporation/). You can try to build a similar page structure to the skeleton, or try the skeleton itself to see how it works.

If you can post your pages folder somewhere, I can take a look.
