### ISSUE TITLE
Contact Form Won't Display

### ISSUE THREAD

**Issue by BrianWilliams28** [tranduyhung/grav-theme-x-corporation#26]
I am trying to build the Contact Us page but when I go to set up the modular page and insert the contact template nothing displays. There is no option to see anything form related in the admin panel either.

All my plug-ins are up to date.

![image](https://user-images.githubusercontent.com/26398392/37214876-65b1ecce-2384-11e8-83fa-cc110cf57ab3.png)

![image](https://user-images.githubusercontent.com/26398392/37214917-855b2130-2384-11e8-842d-0eb3286ff0df.png)

![image](https://user-images.githubusercontent.com/26398392/37214982-b55b9dec-2384-11e8-99ca-08afb4455d2e.png)

Any ideas? I don't want to have to build the contact page from scratch but it's looking like I might have to at this point.

Thanks.

**Comment by tranduyhung** [comment]
Have you created your form in your modular page (the first Contact Us page in your screenshot)? Here is an example: https://raw.githubusercontent.com/tranduyhung/grav-skeleton-x-corporation/master/pages/04.contact/modular.md
You can check the skeleton for sample setup: https://github.com/tranduyhung/grav-skeleton-x-corporation

**Comment by BrianWilliams28** [comment]
No I didn't, although I sorta realized that information was missing. Thank you!
