### ISSUE TITLE
heading scaling

### ISSUE THREAD

**Issue by LeoWinterDE** [tranduyhung/grav-theme-x-corporation#3]
Hello,
the headline does not scale on mobile devices.

![screenshot-peaceofmindwebsite com 2016-08-31 00-02-37](https://cloud.githubusercontent.com/assets/1300141/18108863/ab641fca-6f0e-11e6-8a0b-23e5b59778c8.png)

**Comment by tranduyhung** [comment]
Hi,

Thank you for reporting this! This problem comes from the original HTML template. I will fix it in the next release.

**Comment by LeoWinterDE** [comment]
thanks, that works great.
