### ISSUE TITLE
Client Module should have multi row support

### ISSUE THREAD

**Issue by asifkhanpathan** [tranduyhung/grav-theme-x-corporation#30]
Client module is six column layout but if someone wants to add more client the layout breaks so it need row div wrapper on every six client listing.

**Comment by Ahuahuachi** [comment]
I don't know what you mean with 
> ...the layout breakes...

For me, if i place more than 6 clients the 7th is placed below the first row.
![](https://preview.ibb.co/cT0Awx/Captura.png)

If you want to contribute with code, why don't you create a PR? I'm not understanding well your lines of code.

**Comment by asifkhanpathan** [comment]
![screenshot-2018-4-26](https://user-images.githubusercontent.com/5307187/39330576-b11bc08e-49bf-11e8-817d-a8a842002250.png)

**Comment by tranduyhung** [comment]
1.3.0 has an option to configure the number of clients per row.
