### ISSUE TITLE
Module features (image)

### ISSUE THREAD

**Issue by sjoerdvanhal** [tranduyhung/grav-theme-x-corporation#4]
Where do I need to import the image for the module features. 

When I check the code: 
{{ page.media.images[page.header.image].html() }}

I thought I need to import an image to the page.. But that didn't do the job. 

Hope someone could help me out

**Comment by tranduyhung** [comment]
What you want to achieve exactly ?

```
{{ page.media.images[page.header.image].html() }}
```

is used to show the image which is set in page's header as "image". If you upload your image to page's folder but don't add the image to page's header then your image will not be shown.

**Comment by sjoerdvanhal** [comment]
Thanks for your fast reply.

The image is not visible. I think it goes wrong by add it to the header. I imported the image to the folder and within the features.md I add the following code:

title: introduction
header: 
  image: image.png
features:
    -
        title: 'why?'
        icon: fa-star
...

**Comment by tranduyhung** [comment]
Ensure your page starts with 3 hyphens, I don't see 3 hyphens in the code you posted. It should be similar to this:

```
---
title: introduction
image: image.png
features:
    -
        title: 'why?'
        icon: fa-star
...
```

If the markdown page you you edit is features.md which belongs to a modular page, so the code to show image should be user/templates/modular/features.html.twig, if you post the code 

```
{{ page.media.images[page.header.image].html() }}
```

in a different page, it will not show the image you put in features.md.
