### ISSUE TITLE
Mixed Content

### ISSUE THREAD

**Issue by kraln** [tranduyhung/grav-theme-x-corporation#7]
When served over HTTPS, this theme requests the fonts from google from HTTP, so they are blocked. (example error: Mixed Content: The page was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Montserrat:400,700'. This request has been blocked; the content must be served over HTTPS.)

**Comment by tranduyhung** [comment]
Thank you for letting me know this issue. I just released 1.0.3 to fix it.

**Comment by tranduyhung** [comment]
It is fixed now in 1.0.3.
