### ISSUE TITLE
Page header images in the submenu

### ISSUE THREAD

**Issue by pbt39ppc** [tranduyhung/grav-theme-x-corporation#8]
The image is not showing up, for example on the /about-page, because the server cannot find it. This is because the path to the image is incorrect. It should render as:
http://www.peaceofmindwebsite.com/skeletons/x-corporation/images/e/f/3/0/8/ef3083e15eb7c795025c1e539d2ece7d92e0f44e-img-page-title.jpeg
but currently it renders as:
http://www.peaceofmindwebsite.com/skeletons/skeletons/x-corporation/images/e/f/3/0/8/ef3083e15eb7c795025c1e539d2ece7d92e0f44e-img-page-title.jpeg
You'll need to change how the template interprets the path to find the image.

**Comment by tranduyhung** [comment]
Thank you for reporting this! It is fixed in 1.1.0.
